input {
  tcp {
    port => 5000
    codec => json_lines
    type => "spring-boot"
  }
}

filter {
  if !["@timestamp"] {
    date {
      match => ["timestamp", "ISO8601"]
      target => "@timestamp"
      remove_field => ["timestamp"]
    }
  }

  mutate {
    add_field => { "environment" => "${ENVIRONMENT:development}" }
  }

  if [durationMs] {
    mutate { convert => { "durationMs" => "integer" } }
  }

  if [statusCode] {
    mutate { convert => { "statusCode" => "integer" } }
  }

  mutate {
    remove_field => ["host", "port"]
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    user => "${ELASTICSEARCH_USER:elastic}"
    password => "${ELASTICSEARCH_PASSWORD}"
    index => "demo-app-%{+YYYY.MM.dd}"
    manage_template => true
    template_name => "demo-app"
    template_overwrite => true
  }
}
