package com.demo.app.compliance.service;

import com.demo.app.platform.metrics.SecurityEventRecorder;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.ApplicationArguments;
import org.springframework.boot.ApplicationRunner;
import org.springframework.stereotype.Service;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.security.MessageDigest;
import java.util.ArrayList;
import java.util.HexFormat;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.UUID;

/**
 * SI-7: verifies SHA-256 hashes of critical files at startup against a manifest
 * generated by the CI/CD pipeline. Emits a FILE_INTEGRITY_CHECK_PASSED audit on
 * success, or one FILE_INTEGRITY_VIOLATION audit (plus counter) per affected file
 * on failure. Optionally fail-fasts when app.integrity.fail-on-violation=true.
 *
 * Manifest format (sha256sum-compatible, one entry per line):
 *   &lt;sha256hex&gt;  &lt;/absolute/path/to/file&gt;
 * Lines beginning with '#' and blank lines are ignored.
 */
@Service
@RequiredArgsConstructor
@Slf4j
public class FileIntegrityService implements ApplicationRunner {

    static final UUID SYSTEM_ACTOR = UUID.fromString("00000000-0000-0000-0000-000000000001");

    @Value("${app.integrity.enabled:false}")
    private boolean enabled;

    @Value("${app.integrity.manifest-path:}")
    private String manifestPath;

    @Value("${app.integrity.fail-on-violation:false}")
    private boolean failOnViolation;

    private final AuditService auditService;
    private final SecurityEventRecorder securityEventRecorder;

    @Override
    public void run(ApplicationArguments args) throws Exception {
        if (!enabled) return;
        if (manifestPath.isBlank()) {
            log.warn("SI-7: app.integrity.manifest-path not configured — skipping integrity check");
            return;
        }
        var manifest = Path.of(manifestPath);
        if (!Files.exists(manifest)) {
            log.warn("SI-7: integrity manifest not found at {} — skipping integrity check", manifestPath);
            return;
        }

        var entries = parseManifest(manifest);
        var violations = new ArrayList<String>();

        for (var entry : entries.entrySet()) {
            var filePath = entry.getKey();
            var file = Path.of(filePath);
            if (!Files.exists(file)) {
                violations.add(filePath);
            } else {
                var actual = sha256(file);
                if (!entry.getValue().equalsIgnoreCase(actual)) {
                    violations.add(filePath);
                }
            }
        }

        if (violations.isEmpty()) {
            auditService.log(SYSTEM_ACTOR, "FILE_INTEGRITY_CHECK_PASSED", "System", null, null,
                    Map.of("filesChecked", String.valueOf(entries.size())), "success");
        } else {
            for (var v : violations) {
                auditService.log(SYSTEM_ACTOR, "FILE_INTEGRITY_VIOLATION", "System", null, null,
                        Map.of("file", v), "failure");
                securityEventRecorder.recordIntegrityViolation();
            }
            if (failOnViolation) {
                throw new IllegalStateException("SI-7: file integrity violation detected — " + violations);
            }
        }
    }

    Map<String, String> parseManifest(Path manifest) throws IOException {
        var result = new LinkedHashMap<String, String>();
        for (var line : Files.readAllLines(manifest)) {
            if (line.isBlank() || line.startsWith("#")) continue;
            var parts = line.split("\\s+", 2);
            if (parts.length == 2) {
                result.put(parts[1].trim(), parts[0].trim());
            }
        }
        return result;
    }

    String sha256(Path file) {
        try {
            var md = MessageDigest.getInstance("SHA-256");
            md.update(Files.readAllBytes(file));
            return HexFormat.of().formatHex(md.digest());
        } catch (Exception e) {
            log.warn("SI-7: could not hash {}: {}", file, e.getMessage());
            return "";
        }
    }
}
